version: '3.3'

services:

  db:
    image: mysql:8.1.0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=epay
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    networks:
      - epay

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9201:9200"
    networks:
      - epay

  epay:
    image: itsrd/epay:latest
    container_name: epay-app
    ports:
      - "8080:8080"
    restart: always

    depends_on:
      - db
      - elasticsearch
    environment:
      ELASTIC_DB_HOST: elasticsearch
      ELASTIC_DB_PORT: 9200
      DB_HOST: db:3306
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - epay


networks:
  epay:
    driver: bridge
